CREATE OR REPLACE FUNCTION public.is_admin(user_id uuid) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN RETURN EXISTS (SELECT 1 FROM users WHERE id = user_id AND role = 'admin'); END; $$;
DROP POLICY IF EXISTS "Enable all access for authenticated" ON public.users;
CREATE POLICY "Enable read for everyone" ON public.users FOR SELECT USING (true);
CREATE POLICY "Users can insert own profile" ON public.users FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile or admin" ON public.users FOR UPDATE USING (auth.uid() = id OR is_admin(auth.uid()));
CREATE POLICY "Users can delete own profile or admin" ON public.users FOR DELETE USING (auth.uid() = id OR is_admin(auth.uid()));
DROP POLICY IF EXISTS "Enable all access for authenticated" ON public.orders;
CREATE POLICY "Users can manage own orders" ON public.orders FOR ALL USING (auth.uid() = customer_id OR auth.uid() = worker_id OR auth.uid() = shop_id OR is_admin(auth.uid()));
DROP POLICY IF EXISTS "Enable all access for authenticated" ON public.order_tracking;
CREATE POLICY "Users can manage own order tracking" ON public.order_tracking FOR ALL USING (auth.uid() = user_id OR is_admin(auth.uid()));
DROP POLICY IF EXISTS "Enable all access for authenticated" ON public.notifications;
CREATE POLICY "Users can manage own notifications" ON public.notifications FOR ALL USING (auth.uid() = user_id OR is_admin(auth.uid()));
DROP POLICY IF EXISTS "Enable all access for authenticated" ON public.shops;
CREATE POLICY "Enable read for everyone" ON public.shops FOR SELECT USING (true);
CREATE POLICY "Owners can manage own shop" ON public.shops FOR ALL USING (auth.uid() = user_id OR is_admin(auth.uid()));
DROP POLICY IF EXISTS "Enable all access for authenticated" ON public.workers;
CREATE POLICY "Enable read for everyone" ON public.workers FOR SELECT USING (true);
CREATE POLICY "Owners can manage own worker profile" ON public.workers FOR ALL USING (auth.uid() = user_id OR is_admin(auth.uid()));
DROP POLICY IF EXISTS "Enable all access for authenticated" ON public.shop_applications;
CREATE POLICY "Users can manage own shop applications" ON public.shop_applications FOR ALL USING (auth.uid() = user_id OR is_admin(auth.uid()));
DROP POLICY IF EXISTS "Enable all access for authenticated" ON public.worker_applications;
CREATE POLICY "Users can manage own worker applications" ON public.worker_applications FOR ALL USING (auth.uid() = user_id OR is_admin(auth.uid()));
DROP POLICY IF EXISTS "Enable all access for authenticated" ON public.products;
CREATE POLICY "Enable read for everyone" ON public.products FOR SELECT USING (true);
CREATE POLICY "Owners can manage own products" ON public.products FOR ALL USING (auth.uid() IN (SELECT user_id FROM shops WHERE id = shop_id) OR is_admin(auth.uid()));
DROP POLICY IF EXISTS "Enable all access for authenticated" ON public.shop_items;
CREATE POLICY "Enable read for everyone" ON public.shop_items FOR SELECT USING (true);
CREATE POLICY "Owners can manage own shop items" ON public.shop_items FOR ALL USING (auth.uid() IN (SELECT user_id FROM shops WHERE id = shop_id) OR is_admin(auth.uid()));
DROP POLICY IF EXISTS "Enable all access for authenticated" ON public.shop_sales;
DROP POLICY IF EXISTS "Enable read for everyone" ON public.shop_sales;
CREATE POLICY "Owners can manage own shop sales" ON public.shop_sales FOR ALL USING (auth.uid() IN (SELECT user_id FROM shops WHERE id = shop_id) OR is_admin(auth.uid()));
DROP POLICY IF EXISTS "Enable all access for authenticated" ON public.reviews;
CREATE POLICY "Enable read for everyone" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Users can manage own reviews" ON public.reviews FOR ALL USING (auth.uid() = user_id OR is_admin(auth.uid()));
