export const content = {
  en: {
    nav: {
      location: 'ETAWAH & BANDA',
      callAria: 'Call Go_repario',
      bookWa: 'Book on WhatsApp',
    },
    hero: {
      eyebrow: 'PLUMBING & ELECTRICAL — ETAWAH & BANDA',
      title: "SOMETHING'S BROKEN.",
      titleAccent: "WE'LL FIX IT.",
      sub: 'Message us your problem on WhatsApp. We quote a price up front, and a technician comes to you — no app, no signup, no waiting on hold.',
      cta: 'Book on WhatsApp',
      serving: 'Serving Etawah & Banda',
    },
    services: {
      eyebrow: 'WHAT WE FIX',
      title: 'TWO TRADES. ONE CALL.',
      note: 'Just plumbing and electrical for now — done properly, not spread thin.',
      plumbingTag: 'PLUMBING',
      plumbingJobs: [
        'Leak & pipe repair',
        'Tap & faucet fitting',
        'Bathroom & sink fitting',
        'Water tank & motor issues',
        'Blocked drain clearing',
      ],
      electricalTag: 'ELECTRICAL',
      electricalJobs: [
        'Wiring & rewiring',
        'Switchboard & socket repair',
        'Fan & light installation',
        'Inverter & MCB issues',
        'Short-circuit troubleshooting',
      ],
      priceNote: '₹100 visiting charge for inspection — job price quoted before work starts.',
      bookPlumbing: 'Book plumbing',
      bookElectrical: 'Book electrical',
    },
    howItWorks: {
      eyebrow: 'THE PROCESS',
      title: 'FROM MESSAGE TO FIXED.',
      step1Title: 'Message us',
      step1Detail: 'Tell us the problem and your location on WhatsApp — Etawah or Banda.',
      step2Title: 'Get a quote & time',
      step2Detail: 'We schedule a technician visit (₹100 inspection charge) and provide an upfront quote before work starts.',
      step3Title: 'Technician arrives',
      step3Detail: "The job gets done, and you only pay once you're satisfied it's fixed.",
    },
    whyUs: {
      eyebrow: 'WHY GO_REPARIO',
      title: 'STRAIGHTFORWARD, BY DESIGN.',
      card1Title: 'Local, not a call centre',
      card1Detail: 'Technicians based in Etawah and Banda — not routed through a distant city.',
      card2Title: 'Price before the work starts',
      card2Detail: 'Transparent ₹100 visiting charge for inspection, and full job quote before work starts.',
      card3Title: 'Fast response',
      card3Detail: "Message us and we'll confirm a time slot the same day, wherever possible.",
      card4Title: 'No app, no signup',
      card4Detail: 'Everything happens over WhatsApp, on a number you can save and reuse.',
    },
    footer: {
      titleLine1: 'NEED SOMETHING FIXED IN',
      titleLine2: 'ETAWAH OR BANDA?',
      waBtn: 'Message us on WhatsApp',
      privacy: "We'll only use your WhatsApp number to discuss and schedule your service request.",
      name: 'GO_REPARIO',
      tagline: 'Plumbing & Electrical Repair',
      location: 'Etawah & Banda, Uttar Pradesh',
      rights: 'All rights reserved.',
    },
  },
  hi: {
    nav: {
      location: 'इटावा और बांदा',
      callAria: 'Go_repario को कॉल करें',
      bookWa: 'व्हाट्सएप पर बुक करें',
    },
    hero: {
      eyebrow: 'प्लंबिंग और इलेक्ट्रिकल — इटावा और बांदा',
      title: 'कुछ खराब हो गया?',
      titleAccent: 'हम ठीक कर देंगे।',
      sub: 'व्हाट्सएप पर अपनी समस्या बताएं। हम काम शुरू करने से पहले पक्का रेट बताते हैं और तकनीशियन आपके घर आता है — कोई ऐप या साइनअप नहीं।',
      cta: 'व्हाट्सएप पर बुक करें',
      serving: 'सेवा उपलब्ध: इटावा और बांदा',
    },
    services: {
      eyebrow: 'हम क्या ठीक करते हैं',
      title: 'प्लंबिंग और बिजली, एक ही जगह।',
      note: 'अभी केवल प्लंबिंग और इलेक्ट्रिकल सर्विस — सही काम, पूरा भरोसा।',
      plumbingTag: 'प्लंबिंग (नल व पाइप)',
      plumbingJobs: [
        'लीकेज और पाइप की मरम्मत',
        'नल और टोटी की फिटिंग',
        'बाथरूम और सिंक की फिटिंग',
        'पानी की टंकी और मोटर की समस्या',
        'बंद नाली व ड्रेन सफाई',
      ],
      electricalTag: 'इलेक्ट्रिकल (बिजली)',
      electricalJobs: [
        'वायरिंग और री-वायरिंग',
        'स्विचबोर्ड और सॉकेट मरम्मत',
        'पंखा और लाइट फिटिंग',
        'इन्वर्टर और MCB की समस्या',
        'शॉर्ट-सर्किट ठीक करना',
      ],
      priceNote: '₹100 विज़िटिंग चार्ज — काम शुरू करने से पहले पूरा रेट तय।',
      bookPlumbing: 'प्लंबिंग बुक करें',
      bookElectrical: 'इलेक्ट्रिकल बुक करें',
    },
    howItWorks: {
      eyebrow: 'बुक करने का तरीका',
      title: 'मैसेज करें, काम हो जाएगा।',
      step1Title: 'मैसेज भेजें',
      step1Detail: 'व्हाट्सएप पर अपनी समस्या और लोकेशन (इटावा या बांदा) भेजें।',
      step2Title: 'रेट और समय पाएं',
      step2Detail: 'हम तकनीशियन के आने का समय तय करेंगे (₹100 विज़िटिंग चार्ज) और काम से पहले पक्का रेट बताएंगे।',
      step3Title: 'तकनीशियन आएगा',
      step3Detail: 'काम पूरा होने और आपके संतुष्ट होने पर ही भुगतान करें।',
    },
    whyUs: {
      eyebrow: 'Go_repario ही क्यों?',
      title: 'सीधा काम, बिना किसी झंझट के।',
      card1Title: 'लोकल सर्विस, कोई कॉल सेंटर नहीं',
      card1Detail: 'इटावा और बांदा के स्थानीय तकनीशियन — किसी दूर शहर से कोई एजेंट नहीं।',
      card2Title: 'काम से पहले पक्का रेट',
      card2Detail: 'पारदर्शी ₹100 विज़िटिंग चार्ज और काम शुरू होने से पहले पूरा रेट तय।',
      card3Title: 'त्वरित सेवा',
      card3Detail: 'मैसेज करें और जहां तक संभव हो, उसी दिन तकनीशियन का समय पाएं।',
      card4Title: 'कोई ऐप नहीं, कोई साइनअप नहीं',
      card4Detail: 'सब कुछ सीधे व्हाट्सएप पर होगा — नंबर सेव करें और कभी भी मैसेज करें।',
    },
    footer: {
      titleLine1: 'इटावा या बांदा में',
      titleLine2: 'कुछ ठीक करवाना है?',
      waBtn: 'व्हाट्सएप पर मैसेज करें',
      privacy: 'हम आपके व्हाट्सएप नंबर का उपयोग केवल सर्विस के बारे में बात करने के लिए करेंगे।',
      name: 'GO_REPARIO',
      tagline: 'प्लंबिंग एवं इलेक्ट्रिकल रिपेयर',
      location: 'इटावा व बांदा, उत्तर प्रदेश',
      rights: 'सर्वाधिकार सुरक्षित।',
    },
  },
};
